[INFO   ] Logger: Record log in C:\Users\User\.kivy\logs\kivy_21-07-26_89.txt
[INFO   ] deps: Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "c:\users\user\pycharmprojects\pythonproject1\venv\scripts\python.exe"
[INFO   ] Factory: 186 symbols loaded
[WARNING] Could not find GStreamer plugins. Possible solution: set GST_PLUGIN_PATH
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\eel\__init__.py", line 259, in _process_message
[WARNING] stderr:     return_val = _exposed_functions[message['name']](*message['args'])
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\auto_py_to_exe\ui.py", line 55, in open_folder_in_explorer
[WARNING] stderr:     if not utils.open_output_folder(path):
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\auto_py_to_exe\utils.py", line 31, in open_output_folder
[WARNING] stderr:     os.startfile(folder_directory, 'explore')
[WARNING] stderr: FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Windows\\system32\\output'
[WARNING] stderr: 2021-07-26T10:26:07Z <Greenlet at 0x4152260: _process_message({'call': 7.13907927189765, 'name': 'open_folder_in, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with FileNotFoundError
[WARNING] stderr: 
[WARNING] Could not find GStreamer plugins. Possible solution: set GST_PLUGIN_PATH
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\eel\__init__.py", line 259, in _process_message
[WARNING] stderr:     return_val = _exposed_functions[message['name']](*message['args'])
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\auto_py_to_exe\ui.py", line 55, in open_folder_in_explorer
[WARNING] stderr:     if not utils.open_output_folder(path):
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\auto_py_to_exe\utils.py", line 31, in open_output_folder
[WARNING] stderr:     os.startfile(folder_directory, 'explore')
[WARNING] stderr: FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Windows\\system32\\output'
[WARNING] stderr: 2021-07-26T10:29:23Z <Greenlet at 0x3df0bf0: _process_message({'call': 10.609957377446847, 'name': 'open_folder_, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with FileNotFoundError
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\eel\__init__.py", line 259, in _process_message
[WARNING] stderr:     return_val = _exposed_functions[message['name']](*message['args'])
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\auto_py_to_exe\ui.py", line 55, in open_folder_in_explorer
[WARNING] stderr:     if not utils.open_output_folder(path):
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\auto_py_to_exe\utils.py", line 31, in open_output_folder
[WARNING] stderr:     os.startfile(folder_directory, 'explore')
[WARNING] stderr: FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Windows\\system32\\output'
[WARNING] stderr: 2021-07-26T10:29:24Z <Greenlet at 0x3df0bf0: _process_message({'call': 11.400948125962495, 'name': 'open_folder_, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with FileNotFoundError
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\eel\__init__.py", line 259, in _process_message
[WARNING] stderr:     return_val = _exposed_functions[message['name']](*message['args'])
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\auto_py_to_exe\ui.py", line 55, in open_folder_in_explorer
[WARNING] stderr:     if not utils.open_output_folder(path):
[WARNING] stderr:   File "c:\users\user\pycharmprojects\pythonproject1\venv\lib\site-packages\auto_py_to_exe\utils.py", line 31, in open_output_folder
[WARNING] stderr:     os.startfile(folder_directory, 'explore')
[WARNING] stderr: FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Windows\\system32\\output'
[WARNING] stderr: 2021-07-26T10:29:24Z <Greenlet at 0x3df0bf0: _process_message({'call': 12.032307618660647, 'name': 'open_folder_, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with FileNotFoundError
[WARNING] stderr: 
